### ISSUE TITLE
can't set a gradient as src

### ISSUE THREAD

**Issue by iceberg1369** [IntruderShanky/Frisson#4]
I tried to set a gradient drawbale as my background image, but library doesn't show it
frisson:src="@drawable/gradient"
here is my gradient

<shape   xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <gradient
        android:angle="45"
        android:endColor="#e96443"
        android:startColor="#904e95"
        android:type="linear" />

    <corners
        android:radius="0dp"/>

</shape>

**Comment by IntruderShanky** [comment]
You cant set gradient as source but you can add gradient to the view using these attributes
 ```xml
frisson:gradientType="linear"
frisson:gradient_endColor="#cc000000"
frisson:gradient_startColor="#00000000"
frisson:gradientAngle = "180"
```
